before_script:
  - apk add --update --no-cache curl git docker jq py3-configobj py3-pip py3-setuptools python3 python3-dev
  - pip install awscli
  - go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
  - mkdir -p /root/.docker
  - echo "{ \"credsStore\":\"ecr-login\" }" > /root/.docker/config.json

ansible-2.9:
  extends: .template
  variables:
    AWS_REGION: "us-east-1"
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

ansible-2.9 deploy:
  extends: .template_deploy
  variables:
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10 deploy:
  extends: .template_deploy
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

.template:
  image: golang:alpine3.13
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
  script:
    - docker build -t $REPOSITORY_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
    - docker image ls
  tags:
    - aws
  except:
    - master

.template_deploy:
  image: golang:alpine3.13
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
    DOCKERHUB_URL: leandelivery/docker-ansible-ci
  script:
    - docker build -t $REPOSITORY_URL:$TAG -t $DOCKERHUB_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
    - docker image ls
    - docker push $REPOSITORY_URL:$TAG
    - bash docker_push
  tags:
    - aws
  only:
    - master