stages:
  - build
  - deploy

ansible-2.9 build:
  stage: build
  extends: .template_build
  variables:
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"
  artifacts:
    paths:
      - "9"

ansible-2.10 build:
  stage: build
  extends: .template_build
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"
  artifacts:
    paths:
      - "10"

ansible-2.9 deploy:
  stage: deploy
  extends: .template_deploy
  variables:
    LOCAL_PATH: '9'
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10 deploy:
  stage: deploy
  extends: .template_deploy
  variables:
    LOCAL_PATH: '10'
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

.template_build:
  image: docker:latest
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
  before_script:
    - apk add --update --no-cache curl jq py3-configobj py3-pip py3-setuptools python3 python3-dev
    - pip install awscli
  script:
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ECR_REPO
    - docker build -t $REPOSITORY_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
  tags:
    - aws

.template_deploy:
  image: docker:latest
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
  script:
    - docker image ls
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ECR_REPO
    - docker push $REPOSITORY_URL:$TAG
  tags:
    - aws
  # only:
  #   - master