ansible-2.9:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

# ansible-2.7:
#   extends: .template
#   variables:
#     ANSIBLE_VERSION: "2.7.*"
#     MOLECULE_VERSION: "2.22"
#     TAG: "ansible-2.7"

.template:
  image: "docker:latest"
  variables:
    REPOSITORY_URL: "998383315469.dkr.ecr.us-east-1.amazonaws.com/docker-ansible-ci"
  before_script:
    - apk add --update --no-cache curl jq py3-configobj py3-pip py3-setuptools python3 python3-dev
    - pip install awscli
  script:
#    - $(aws ecr get-login --no-include-email --region us-east-1)
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 998383315469.dkr.ecr.us-east-1.amazonaws.com
    - docker build -t $REPOSITORY_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
    - docker push $REPOSITORY_URL:$TAG
  tags:
    - aws
