before_script:
  - apk add --update --no-cache curl jq py3-configobj py3-pip py3-setuptools python3 python3-dev
  - pip install awscli
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ECR_REPO

ansible-2.9:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10:
  extends: .template
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

ansible-2.9 deploy:
  extends: .template_deploy
  variables:
    ANSIBLE_VERSION: "2.9.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.9"

ansible-2.10 deploy:
  extends: .template_deploy
  variables:
    ANSIBLE_VERSION: "2.10.*"
    MOLECULE_VERSION: "3.*"
    TAG: "ansible-2.10"

.template:
  image: docker:latest
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
  script:
    - docker build -t $REPOSITORY_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
    - docker image ls
  tags:
    - aws
  except:
    - master

.template_deploy:
  image: docker:latest
  variables:
    REPOSITORY_URL: $AWS_ECR_REPO/docker-ansible-ci
  script:
    - docker build -t $REPOSITORY_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
    - docker image ls
    - docker push $REPOSITORY_URL:$TAG
  tags:
    - aws
  only:
    - master