---
name: CI
on:
  push:
    branches:
      - master
env:
  DOCKERHUB_URL: leandelivery/docker-ansible-ci
  DOCKERHUB_USERNAME: leandeliveryrobot
  MOLECULE_VERSION: "3.*"
jobs:
  ansible-2_9:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ansible-2.9
          ANSIBLE_VERSION: 2.9.*
        run: |
          docker build -t $DOCKERHUB_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
          docker image ls
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_URL:$TAG
          docker logout
  ansible-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ansible-3
          ANSIBLE_VERSION: 3.*
        run: |
          docker build -t $DOCKERHUB_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
          docker image ls
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_URL:$TAG
          docker logout
  ansible-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        env:
          TAG: ansible-4
          ANSIBLE_VERSION: 4.*
        run: |
          docker build -t $DOCKERHUB_URL:$TAG --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION --build-arg MOLECULE_VERSION=$MOLECULE_VERSION .
          docker image ls
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $DOCKERHUB_URL:$TAG
          docker logout
